#spring.application.name=msaConfig

server:
  port: 8761

spring:
  application:
    name: discoveryservice # ???? ??? ???? ??

eureka:
  client:
    register-with-eureka: false # ???? ???? ??(??? ?? ???? ???????? true? ???? ?? ??? ???? ????? ?)
    fetch-registry: false # ????? ???? ?? ???? ??? ???, ????? ????? false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
















