#spring.application.name=solo
server:
  port: 8443
  ssl:
    enabled: true
    key-store: /Users/bighwang/Documents/workspace/solo/src/main/java/resources/solo_ssl.jks
    key-store-password: sololocalhostssl
    key-store-type: JKS
    key-alias: solo_localhost_ssl
  http:
    port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/solo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: localhost
    port: 6379
#  datasource:
#    url: jdbc:mariadb://localhost:3306/solo     #{????????::????? mystudy}
#    username: solo
#    password: solo
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
  thymeleaf:
    enabled: true
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML
    check-template: true
    check-template-location: true

jwt:
  secret: 63fba97a41e0d004e10e8dbbcb9a547819280efb00a54c732aca36a8a58258e4fcc539ffc5159a7f0a7be78b86efe001c12ba6af6debeb0a89e8ce7e82e75455
  access:
    expiration: 800
    header: Authorization
  refresh:
    expiration: 900
    header: Authorization-refresh

logging:
  level:
    org.springframework: info