#spring.application.name=vedio

server:
  #  port: 8080
  port: 0

spring:
  application:
    name: my-video-service
  thymeleaf:
    enabled: true
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML
    check-template: true
    check-template-location: true

logging:
  level:
    org.springframework: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

greeting:
  message: Welcome to the SOLO video Application.



























